package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/uteamup/cli/internal/imageanalyzer/models"
)

// GenerateSummaryReport creates a Markdown summary report and writes it to
// outputFolder/summary_report.md. Returns the report text.
func (e *CSVExporter) GenerateSummaryReport(
	groups []models.ImageGroup,
	unclassified []models.ImageAnalysisResult,
	durationSeconds float64,
	duplicatesFound int,
) (string, error) {
	totalImages := len(unclassified)
	for _, g := range groups {
		totalImages += len(g.AllImagePaths())
	}

	flagged := 0
	for _, g := range groups {
		if g.Primary.FlaggedForReview {
			flagged++
		}
	}
	for _, r := range unclassified {
		if r.FlaggedForReview {
			flagged++
		}
	}

	// Per-type counts.
	typeCounts := make(map[string]int)
	for _, g := range groups {
		t := string(g.Primary.Classification.PrimaryType)
		typeCounts[t]++
	}
	if len(unclassified) > 0 {
		typeCounts["unclassified"] = len(unclassified)
	}

	minutes := durationSeconds / 60.0

	var b strings.Builder
	b.WriteString("# Image Analysis Summary Report\n\n")
	b.WriteString(fmt.Sprintf("**Date:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString("## Overview\n\n")
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Total images processed | %d |\n", totalImages))
	b.WriteString(fmt.Sprintf("| Groups formed | %d |\n", len(groups)))
	b.WriteString(fmt.Sprintf("| Flagged for review | %d |\n", flagged))
	b.WriteString(fmt.Sprintf("| Duplicates found | %d |\n", duplicatesFound))
	b.WriteString(fmt.Sprintf("| Processing duration | %.1f min (%.0fs) |\n", minutes, durationSeconds))
	b.WriteString("\n## Results by Type\n\n")
	b.WriteString("| Entity Type | Count |\n")
	b.WriteString("|-------------|-------|\n")

	// Sort type names for deterministic output.
	sortedTypes := make([]string, 0, len(typeCounts))
	for t := range typeCounts {
		sortedTypes = append(sortedTypes, t)
	}
	sort.Strings(sortedTypes)
	for _, t := range sortedTypes {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", t, typeCounts[t]))
	}

	b.WriteString("\n---\n")
	b.WriteString("*Generated by UteamUP Image Analyzer*\n")

	report := b.String()

	reportPath := filepath.Join(e.outputFolder, "summary_report.md")
	if err := os.WriteFile(reportPath, []byte(report), 0o644); err != nil {
		return "", fmt.Errorf("writing summary report: %w", err)
	}
	return report, nil
}
