package registry

func assetRentalLifecycleActions() []Action {
	return []Action{
		{Name: "info", Description: "Info a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalGetByAsset", HTTPMethod: "GET", RESTPath: "asset/by-guid/{assetGuid}", Args: []ArgDef{{Name: "assetGuid", Description: "Public asset GUID", Required: true, Type: "uuid"}}},
		{Name: "history", Description: "History a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalGetHistory", HTTPMethod: "GET", RESTPath: "asset/by-guid/{assetGuid}/history", Args: []ArgDef{{Name: "assetGuid", Description: "Public asset GUID", Required: true, Type: "uuid"}}},
		{Name: "configure", Description: "Configure a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalCreateOrUpdate", HTTPMethod: "POST", RESTPath: "asset/by-guid/{assetGuid}", Args: []ArgDef{{Name: "assetGuid", Description: "Public asset GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "reserve", Description: "Reserve a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalStart", HTTPMethod: "POST", RESTPath: "asset/by-guid/{assetGuid}/reservations", Args: []ArgDef{{Name: "assetGuid", Description: "Public asset GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "extend", Description: "Extend a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalExtend", HTTPMethod: "POST", RESTPath: "by-guid/{rentalGuid}/extend", Args: []ArgDef{{Name: "rentalGuid", Description: "Public rental GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "cancel", Description: "Cancel a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalCancel", HTTPMethod: "POST", RESTPath: "by-guid/{rentalGuid}/cancel", Args: []ArgDef{{Name: "rentalGuid", Description: "Public rental GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "checkout", Description: "Checkout a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalCheckout", HTTPMethod: "POST", RESTPath: "by-guid/{rentalGuid}/checkout", Args: []ArgDef{{Name: "rentalGuid", Description: "Public rental GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "return", Description: "Return a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalEnd", HTTPMethod: "POST", RESTPath: "by-guid/{rentalGuid}/return", Args: []ArgDef{{Name: "rentalGuid", Description: "Public rental GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
		{Name: "ready", Description: "Ready a rental using public GUIDs and reviewed evidence", ToolName: "UteamupAssetrentalReady", HTTPMethod: "POST", RESTPath: "asset/by-guid/{assetGuid}/ready", Args: []ArgDef{{Name: "assetGuid", Description: "Public asset GUID", Required: true, Type: "uuid"}}, Flags: []FlagDef{{Name: "request-file", Short: "f", BodyName: "model", Description: "JSON canonical rental request; UTC dates, GUID links and expectedUpdatedAtUtc for mutations", Required: true, Type: "string", JSONFile: true}}},
	}
}
