package registry

func init() {
	Register(&Domain{
		Name:        "itmanagement",
		Aliases:     []string{"it", "it-management"},
		Description: "Inspect the selected tenant's IT Management connection, alerts, rules, resources and network flows",
		// Routes mirror the IT Management controllers. Without explicit paths every action fell back
		// to GET /api/itmanagement, which is not a route, so each command answered 404.
		APIPath: "/api/itmanagement",
		Actions: []Action{
			{
				Name:        "dashboard",
				Description: "Show connection health, open alerts by severity, servers, patching and unmapped resources",
				ToolName:    "UteamupITManagementDashboard",
				HTTPMethod:  "GET",
				RESTPath:    "dashboard",
			},
			{
				Name:        "alerts",
				Description: "List IT alerts with state, severity, source, asset and time filters",
				ToolName:    "UteamupITManagementAlertsList",
				HTTPMethod:  "GET",
				RESTPath:    "alerts",
				Flags: []FlagDef{
					{Name: "state", Description: "open, acknowledged or resolved", Type: "string"},
					{Name: "severity", BodyName: "minimumSeverity", Description: "Minimum severity: info, warning, error or critical", Type: "string"},
					{Name: "source", Description: "Source filter (for example securityAlert, heartbeat, networkFlow)", Type: "string"},
					{Name: "asset-guid", BodyName: "assetGuid", Description: "Asset GUID filter", Type: "string"},
					{Name: "rule-guid", BodyName: "ruleGuid", Description: "Rule GUID filter", Type: "string"},
					{Name: "from", Description: "UTC range start (ISO-8601)", Type: "string"},
					{Name: "to", Description: "UTC range end (ISO-8601)", Type: "string"},
					{Name: "search", Description: "Title, resource or computer contains", Type: "string"},
					{Name: "limit", BodyName: "pageSize", Description: "Page size (1-200)", Type: "int", Default: 50},
					{Name: "page", Description: "Page number", Type: "int", Default: 1},
				},
			},
			{
				Name:        "alert",
				Description: "Show one IT alert",
				ToolName:    "UteamupITManagementAlertGet",
				HTTPMethod:  "GET",
				RESTPath:    "alerts/{alertGuid}",
				Args: []ArgDef{
					{Name: "alert-guid", BodyName: "alertGuid", Description: "Alert GUID", Type: "non-empty-uuid", Required: true},
				},
			},
			{
				Name:        "alert-ack",
				Description: "Acknowledge an IT alert with a reason code",
				ToolName:    "UteamupITManagementAlertAcknowledge",
				HTTPMethod:  "POST",
				RESTPath:    "alerts/{alertGuid}/acknowledge",
				Args: []ArgDef{
					{Name: "alert-guid", BodyName: "alertGuid", Description: "Alert GUID", Type: "non-empty-uuid", Required: true},
				},
				Flags: []FlagDef{
					{Name: "reason", BodyName: "reasonCode", Description: "falsePositive, fixed, duplicate, plannedMaintenance, expected or other", Type: "string"},
					{Name: "note", Description: "Optional note", Type: "string"},
				},
			},
			{
				Name:        "alert-resolve",
				Description: "Resolve an IT alert with a reason code",
				ToolName:    "UteamupITManagementAlertResolve",
				HTTPMethod:  "POST",
				RESTPath:    "alerts/{alertGuid}/resolve",
				Args: []ArgDef{
					{Name: "alert-guid", BodyName: "alertGuid", Description: "Alert GUID", Type: "non-empty-uuid", Required: true},
				},
				Flags: []FlagDef{
					{Name: "reason", BodyName: "reasonCode", Description: "falsePositive, fixed, duplicate, plannedMaintenance, expected or other", Type: "string"},
					{Name: "note", Description: "Optional note", Type: "string"},
				},
			},
			{
				Name:        "rules",
				Description: "List IT alert rules with their noise controls and simulation state",
				ToolName:    "UteamupITManagementRulesList",
				HTTPMethod:  "GET",
				RESTPath:    "rules",
			},
			{
				Name:        "connections",
				Description: "Show Azure connection health (status only, never secrets). Each row is named after its Entra directory.",
				ToolName:    "UteamupITManagementConnectionsList",
				HTTPMethod:  "GET",
				RESTPath:    "connections",
			},
			{
				Name:        "connections-quota",
				Description: "How many Entra directories this tenant may still connect",
				ToolName:    "UteamupITManagementConnectionsQuota",
				HTTPMethod:  "GET",
				RESTPath:    "connections/quota",
			},
			{
				Name:        "resources",
				Description: "List discovered Azure resources and their asset mapping",
				ToolName:    "UteamupITManagementResourcesList",
				HTTPMethod:  "GET",
				RESTPath:    "resources",
				Flags: []FlagDef{
					{Name: "mapped", Description: "Only resources linked to an asset (--mapped) or only unlinked ones (--mapped=false)", Type: "bool"},
					{Name: "include-stale", BodyName: "includeStale", Description: "Include resources not seen for 30 days", Type: "bool"},
					{Name: "type", BodyName: "resourceType", Description: "Azure resource type filter", Type: "string"},
					{Name: "search", Description: "Name, resource group or computer contains", Type: "string"},
					{Name: "asset-guid", BodyName: "assetGuid", Description: "Only the resource linked to this asset GUID", Type: "string"},
					{Name: "limit", BodyName: "pageSize", Description: "Page size (1-200)", Type: "int", Default: 50},
					{Name: "page", Description: "Page number", Type: "int", Default: 1},
				},
			},
			{
				Name:        "resource-children",
				Description: "List the disks, network cards and public IPs that hang off one discovered resource",
				ToolName:    "UteamupITManagementResourceChildren",
				HTTPMethod:  "GET",
				RESTPath:    "resources/{resourceGuid}/children",
				Flags: []FlagDef{
					{Name: "resource-guid", BodyName: "resourceGuid", Description: "The parent resource GUID", Type: "string", Required: true},
				},
			},
			{
				Name:        "resource-proposals",
				Description: "Read UPMate's verdicts on which discovered resources should become assets",
				ToolName:    "UteamupITManagementResourceProposals",
				HTTPMethod:  "GET",
				RESTPath:    "resources/proposals",
				Flags: []FlagDef{
					{Name: "connection-guid", BodyName: "connectionGuid", Description: "Limit to one connection GUID", Type: "string"},
				},
			},
			{
				Name:        "servicemap",
				Description: "Show the service map: mapped assets, accepted and proposed connections with flow evidence",
				ToolName:    "UteamupITManagementServiceMapSummary",
				HTTPMethod:  "GET",
				RESTPath:    "servicemap",
				Flags: []FlagDef{
					{Name: "window-hours", BodyName: "windowHours", Description: "Flow window in hours (1-168)", Type: "int", Default: 24},
					{Name: "subscription-id", BodyName: "subscriptionIds", Description: "Azure subscription to build the map from, repeatable", Type: "stringSlice"},
					{Name: "resource-group", BodyName: "resourceGroups", Description: "Azure resource group to build the map from, repeatable", Type: "stringSlice"},
					{Name: "location", BodyName: "locations", Description: "Azure region to build the map from, repeatable", Type: "stringSlice"},
					{Name: "resource-guid", BodyName: "resourceGuids", Description: "Resource GUID to build the map around; the map is these plus what they talk to, repeatable", Type: "stringSlice"},
					{Name: "max-nodes", BodyName: "maxNodes", Description: "Node cap applied after scoping (10-2000)", Type: "int", Default: 300},
				},
			},
			{
				Name:        "flows",
				Description: "List network flows over a window, optionally for one asset",
				ToolName:    "UteamupITManagementFlowsSummary",
				HTTPMethod:  "GET",
				RESTPath:    "network/flows",
				Flags: []FlagDef{
					{Name: "asset-guid", BodyName: "assetGuid", Description: "Asset GUID on either end of the flow", Type: "string"},
					{Name: "window-hours", BodyName: "windowHours", Description: "Flow window in hours (1-168)", Type: "int", Default: 24},
					{Name: "direction", Description: "in or out", Type: "string"},
					{Name: "port", Description: "Destination port", Type: "int"},
					{Name: "protocol", Description: "tcp or udp", Type: "string"},
					{Name: "denied-only", BodyName: "deniedOnly", Description: "Only flows an NSG denied", Type: "bool"},
					{Name: "limit", BodyName: "pageSize", Description: "Page size (1-200)", Type: "int", Default: 50},
					{Name: "page", Description: "Page number", Type: "int", Default: 1},
				},
			},
			{
				Name:        "activity",
				Description: "Show the Azure activity log for the connected subscriptions (callers masked)",
				ToolName:    "UteamupITManagementActivityLog",
				HTTPMethod:  "GET",
				RESTPath:    "logs/activity",
				Flags: []FlagDef{
					{Name: "from", BodyName: "fromUtc", Description: "UTC range start (ISO-8601)", Type: "string"},
					{Name: "to", BodyName: "toUtc", Description: "UTC range end (ISO-8601)", Type: "string"},
					{Name: "failed-only", BodyName: "failedOnly", Description: "Only failed operations", Type: "bool"},
					{Name: "search", BodyName: "textContains", Description: "Free-text filter (max 200 characters)", Type: "string"},
					{Name: "resource-group", BodyName: "resourceGroup", Description: "Resource group filter", Type: "string"},
					{Name: "subscription-id", BodyName: "subscriptionId", Description: "Azure subscription GUID filter", Type: "string"},
					{Name: "limit", BodyName: "rowLimit", Description: "Maximum rows (1-500)", Type: "int", Default: 200},
				},
			},
		},
	})
}
